blog/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from blogpages import views
from search import views as search_views
from wagtail.images.views.serve import ServeView

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    re_path(r'^images/([^/]*)/(\d*)/([^/]*)/[^/]*$', ServeView.as_view(), name='wagtailimages_serve'),
    path('blog/create/', views.blog_create, name='blog_create'),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

blogpages/models.py
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page


class BlogIndex(Page):
    template = 'blogpages/blog_index.html'
    max_count = 1
    parent_page_types = ['home.HomePage']
    subpage_types = ['blogpages.BlogDetail']

    subtitle = models.CharField(max_length=100,  null=True)
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('subtitle'),
        FieldPanel('body'),
    ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        context['blogpages'] = BlogDetail.objects.live().public
        return context

class BlogDetail(Page):
    parent_page_types = ['blogpages.BlogIndex']
    subpage_types = []  #BlogDetail 의 child page 생성금지
    subtitle = models.CharField(max_length=100, null=True)
    body = RichTextField(blank=True, features=['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link'])

    content_panels = Page.content_panels + [
        FieldPanel('subtitle'),
        FieldPanel('body'),
    ]

documents/models.py
from django.db import models

from wagtail.documents.models import AbstractDocument, Document


class CustomDocument(AbstractDocument):
    description = models.CharField(blank=True, max_length=255)

    admin_form_fields = Document.admin_form_fields + (
        "description",
    )

home/models.py
from django.db import models
from wagtail.admin.panels import FieldPanel
from wagtail.documents import get_document_model
from wagtail.fields import RichTextField
from wagtail.images import get_image_model

from wagtail.models import Page


class HomePage(Page):
    max_count = 1
    subtitle = models.CharField("부제",max_length=100, blank=True, null=True)
    body = RichTextField(blank=True)
    image = models.ForeignKey(
        get_image_model(),  # 'wagtailimages.Image' can be used as a string
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    custom_document = models.ForeignKey(
        get_document_model(),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    content_panels = Page.content_panels + [
        FieldPanel("subtitle", read_only=True),
        FieldPanel("body"),
        FieldPanel("image"),
        FieldPanel("custom_document"),
    ]

images/models.py
from django.db import models
from wagtail.images.models import Image, AbstractImage, AbstractRendition


class CustomImage(AbstractImage):
    caption = models.CharField(max_length=255, blank=True)

    admin_form_fields = Image.admin_form_fields + ('caption',)


class CustomRendition(AbstractRendition):
    image = models.ForeignKey(CustomImage, on_delete=models.CASCADE, related_name='renditions')

    class Meta:
        unique_together = (
            ('image', 'filter_spec', 'focal_point_key'),
        )

blogpages/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from blogpages.models import BlogDetail



class BlogDetailForm(forms.ModelForm):
    class Meta:
        model = BlogDetail
        fields = ['title', 'subtitle', 'body']
        widgets = {
            'body': CKEditorWidget(),
        }

blogpages/views.py
from django.shortcuts import render, redirect
from blogpages.models import BlogDetail, BlogIndex
from .forms import BlogDetailForm

def blog_create(request):
    if request.method == 'POST':
        form = BlogDetailForm(request.POST)
        if form.is_valid():
            blog_detail = form.save(commit=False)

            # 1. BlogIndex 부모 페이지 찾기
            blog_index = BlogIndex.objects.first()  # 필요하면 id로 특정 BlogIndex 찾기

            # 2. 제목은 이미 form.save(commit=False)로 채워짐

            # 3. Wagtail 페이지 트리에 추가
            blog_index.add_child(instance=blog_detail)

            # 4. Revision 저장하고, publish로 바로 공개
            blog_detail.save_revision().publish()

            # 5. 저장 후 BlogIndex 목록 페이지로 리다이렉트
            return redirect(blog_index.url)
    else:
        form = BlogDetailForm()

    return render(request, 'blogpages/blog_create.html', {'form': form})

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page

# To enable logging of search queries for use with the "Promoted search results" module
# <https://docs.wagtail.org/en/stable/reference/contrib/searchpromotions.html>
# uncomment the following line and the lines indicated in the search function
# (after adding wagtail.contrib.search_promotions to INSTALLED_APPS):

# from wagtail.contrib.search_promotions.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)

        # To log this query for use with the "Promoted search results" module:

        # query = Query.get(search_query)
        # query.add_hit()

    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

blog/templates/base.html
{% load static wagtailcore_tags wagtailuserbar %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
            {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
            {% endblock %}

            {% block title_suffix %}
            {% wagtail_site as current_site %}
            {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
            {% endblock %}
        </title>
        {% if page.search_description %}
        <meta name="description" content="{{ page.search_description }}" />
        {% endif %}
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Force all links in the live preview panel to be opened in a new tab #}
        {% if request.in_preview_panel %}
        <base target="_blank">
        {% endif %}

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">

        {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}
        {% endblock %}
        <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
        <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}

        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

        {% block extra_js %}
        {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>

blog/templates/blogpages/blog_create.html
{% extends "base.html" %}
{% load django_bootstrap5 widget_tweaks wagtailcore_tags %}

{% block extra_head %}
  <link rel="stylesheet" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
  <script src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <h1 class="mb-4">블로그 글 작성하기</h1>

    <form method="post">
      {% csrf_token %}

      <div class="mb-3">
        <label for="id_title" class="form-label">제목</label>
        {{ form.title|add_class:"form-control" }}
      </div>

      <div class="mb-3">
        <label for="id_subtitle" class="form-label">부제목</label>
        {{ form.subtitle|add_class:"form-control" }}
      </div>

      <div class="mb-3">

        <label for="id_body" class="form-label">내용</label>
        {{ form.body }}
    </div>

      </div>

      <button type="submit" class="btn btn-primary">작성 완료</button>
    </form>
  </div>
{% endblock %}

blog/templates/blogpages/blog_detail.html
{% extends 'base.html' %}
{% load wagtailcore_tags %}

{% block content %}

<h1>{{ page.title }}</h1>
<h1>{{ page.subtitle }}</h1>
{{ page.body | richtext}}

{% endblock  %}

blog/templates/blogpages/blog_index.html
{% extends 'base.html' %}
{% load wagtailcore_tags %}

{% block content %}

<h1>{{ page.title }}</h1>
<h1>{{ page.subtitle }}</h1>
{{ page.body | richtext}}


<hr>

{% for blog_post in blogpages %}
    <a href="{{ blog_post.url }}">{{ blog_post.id}}. {{ blog_post.title }}</a>
    {{ blog_post.subtitle }} {{ blog_post.latest_revision_created_at }}
<hr>

{% endfor %}

{% endblock  %}

home/templates/home/home_page.html
{% extends "base.html" %}
{% load wagtailcore_tags wagtailimages_tags  %}
{% block content %}

{% if page.custom_document %}
    <a href="{{ page.custom_document.url }}">{{ page.custom_document.title }}</a>
{% endif %}

{% endblock content %}

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
<h1>Search</h1>

<form action="{% url 'search' %}" method="get">
    <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
    <input type="submit" value="Search" class="button">
</form>

{% if search_results %}
<ul>
    {% for result in search_results %}
    <li>
        <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
        {% if result.search_description %}
        {{ result.search_description }}
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if search_results.has_previous %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
{% endif %}

{% if search_results.has_next %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
{% endif %}
{% elif search_query %}
No results found
{% endif %}
{% endblock %}